POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Implc3NldHVtIiwiaWQiOiI2NzhjZGU1ZjI0YTdkZTg1YjU2YjYzMWYiLCJpYXQiOjE3MzcyODUyNDB9.FS-A9-Y3WwEZALQ8TLkBbiz_W3IUe-zCkE7ZbRk1NLk

{
  "title": "bruhgingnewwithuser",
  "author": "Jesdsdssse Tenhula",
  "url": "bingussadfad-site.com",
  "likes": -34
}  